Repository Winterpuma/bmstu_team-development, pull requests merged in 2021-05, with the labels that each got.

#47 Создание сцены с информацией об авторах
  SimpleStory/Assets/Pixel Adventure 1/Menu/Buttons/unnamed.png
  SimpleStory/Assets/Pixel Adventure 1/Menu/Buttons/unnamed.png.meta
  SimpleStory/Assets/Scenes/AboutAuthors.unity
  SimpleStory/Assets/Scenes/AboutAuthors.unity.meta
  SimpleStory/Assets/Scripts/Menu.cs
  SimpleStory/Assets/photo.meta
  SimpleStory/Assets/photo/dima.png
  SimpleStory/Assets/photo/dima.png.meta
  SimpleStory/Assets/photo/nastya.png
  SimpleStory/Assets/photo/nastya.png.meta
  SimpleStory/Assets/photo/tanya.png
  SimpleStory/Assets/photo/tanya.png.meta
  SimpleStory/Assets/photo/yana.png
  SimpleStory/Assets/photo/yana.png.meta
  SimpleStory/ProjectSettings/EditorBuildSettings.asset
Labels: frontend

#49 Добавлена автоматическая документация
  .github/workflows/documentation.yml
  .github/workflows/main.yml
  Documentation/Doxyfile
Labels: documentation

#51 Добавление на экран игры кнопки возвращения в меню
  SimpleStory/Assets/Scenes/FirstLevel.unity
Labels: frontend

#55 Добавить сцену финиша
  SimpleStory/Assets/Scenes/Finish.unity
  SimpleStory/Assets/Scenes/Finish.unity.meta
Labels: frontend

#58 Изменил прыжок
  SimpleStory/Assets/Scripts/Creatures/Player.cs
Labels: backend, bug

#59 Добавил комменты в классе Creature
  SimpleStory/Assets/Scripts/Creatures/Creature.cs
Labels: documentation

#61 Пофиксил дурацкий баг с непрогрузкой экрана победы #53
  SimpleStory/ProjectSettings/EditorBuildSettings.asset
Labels: backend, bug

#60 Добавлены тесты в код и github actions
  .github/workflows/main.yml
  SimpleStory/Assets/Scripts/GameAssembly.asmdef
  SimpleStory/Assets/Scripts/GameAssembly.asmdef.meta
  SimpleStory/Assets/Tests.meta
  SimpleStory/Assets/Tests/TestHelper.cs
  SimpleStory/Assets/Tests/TestHelper.cs.meta
  SimpleStory/Assets/Tests/TestSuite.cs
  SimpleStory/Assets/Tests/TestSuite.cs.meta
  SimpleStory/Assets/Tests/Tests.asmdef
  SimpleStory/Assets/Tests/Tests.asmdef.meta
  SimpleStory/Assets/Tests/WaitForSceneLoaded.cs
  SimpleStory/Assets/Tests/WaitForSceneLoaded.cs.meta
  SimpleStory/ProjectSettings/ProjectSettings.asset
Labels: CI/CD

#62 Refactor and comment code
  SimpleStory/Assets/Scripts/Camera/CameraFollow2D.cs
  SimpleStory/Assets/Scripts/Creatures/Creature.cs
  SimpleStory/Assets/Scripts/Creatures/Player.cs
  SimpleStory/Assets/Scripts/Menu.cs
  SimpleStory/Assets/Scripts/Triggers/DeathTrigger.cs
  SimpleStory/Assets/Scripts/Triggers/LevelEndTrigger.cs
Labels: documentation

#63 Добавлено readme описание проекта
  README.md
Labels: enhancement

#64 Релиз приложения
  .github/workflows/documentation.yml
  .github/workflows/main.yml
  Documentation/Doxyfile
  README.md
  SimpleStory/Assets/Pixel Adventure 1/Menu/Buttons/unnamed.png
  SimpleStory/Assets/Pixel Adventure 1/Menu/Buttons/unnamed.png.meta
  SimpleStory/Assets/Scenes/AboutAuthors.unity
  SimpleStory/Assets/Scenes/AboutAuthors.unity.meta
  SimpleStory/Assets/Scenes/Finish.unity
  SimpleStory/Assets/Scenes/Finish.unity.meta
  SimpleStory/Assets/Scenes/FirstLevel.unity
  SimpleStory/Assets/Scripts/Camera/CameraFollow2D.cs
  SimpleStory/Assets/Scripts/Creatures/Creature.cs
  SimpleStory/Assets/Scripts/Creatures/Player.cs
  SimpleStory/Assets/Scripts/GameAssembly.asmdef
  SimpleStory/Assets/Scripts/GameAssembly.asmdef.meta
  SimpleStory/Assets/Scripts/Menu.cs
  SimpleStory/Assets/Scripts/Triggers.meta
  SimpleStory/Assets/Scripts/Triggers/DeathTrigger.cs
  SimpleStory/Assets/Scripts/Triggers/DeathTrigger.cs.meta
  SimpleStory/Assets/Scripts/Triggers/LevelEndTrigger.cs
  SimpleStory/Assets/Scripts/Triggers/LevelEndTrigger.cs.meta
  SimpleStory/Assets/Tests.meta
  SimpleStory/Assets/Tests/TestHelper.cs
  SimpleStory/Assets/Tests/TestHelper.cs.meta
  SimpleStory/Assets/Tests/TestSuite.cs
  SimpleStory/Assets/Tests/TestSuite.cs.meta
  SimpleStory/Assets/Tests/Tests.asmdef
  SimpleStory/Assets/Tests/Tests.asmdef.meta
  SimpleStory/Assets/Tests/WaitForSceneLoaded.cs
  SimpleStory/Assets/Tests/WaitForSceneLoaded.cs.meta
  SimpleStory/Assets/photo.meta
  SimpleStory/Assets/photo/dima.png
  SimpleStory/Assets/photo/dima.png.meta
  SimpleStory/Assets/photo/nastya.png
  SimpleStory/Assets/photo/nastya.png.meta
  SimpleStory/Assets/photo/tanya.png
  SimpleStory/Assets/photo/tanya.png.meta
  SimpleStory/Assets/photo/yana.png
  SimpleStory/Assets/photo/yana.png.meta
  SimpleStory/ProjectSettings/EditorBuildSettings.asset
  SimpleStory/ProjectSettings/ProjectSettings.asset
  SimpleStory/ProjectSettings/TagManager.asset
Labels: CI/CD, backend, documentation, enhancement, frontend
