Repository Winterpuma/bmstu_team-development, pull requests merged in 2021-04, with the labels that each got.

#34 Изменил доступ к полям данным и методам класса существа
  SimpleStory/Assets/Scripts/Creatures/Creature.cs
Labels: backend

#35 Создал класс персонажа и небольшую сцену для теста #18 #20
  SimpleStory/Assets/Scenes/PlayerTest.unity
  SimpleStory/Assets/Scenes/PlayerTest.unity.meta
  SimpleStory/Assets/Scripts/Creatures/Player.cs
  SimpleStory/Assets/Scripts/Creatures/Player.cs.meta
Labels: backend

#38 Add cameraFollow2d and link it to test player #37
  SimpleStory/Assets/Scenes/PlayerTest.unity
  SimpleStory/Assets/Scripts/Camera.meta
  SimpleStory/Assets/Scripts/Camera/CameraFollow2D.cs
  SimpleStory/Assets/Scripts/Camera/CameraFollow2D.cs.meta
Labels: backend

#39 Добавлены Github Actions для пул реквесов
  .github/workflows/activation.yml
  .github/workflows/main.yml
Labels: CI/CD

#44 Добавить Uml диаграмму
  wiki/uml-diagram/uml-diagram.drawio
Labels: documentation

#45 Создание первого уровня игры + bugfix
  SimpleStory/Assets/Pixel Adventure 1/Terrain/Terrain (16x16).png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/justTerrain.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/justTerrain/terrain_left.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/justTerrain/terrain_left.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/justTerrain/terrain_middle.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/justTerrain/terrain_middle.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/justTerrain/terrain_right.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/justTerrain/terrain_right.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/terrain.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_down.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_down.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_down_left.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_down_left.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_down_right.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_down_right.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_left.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_left.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_middle.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_middle.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_right.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/underTerrain/underTerrain_right.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/upTerrian.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/upTerrian/upTerrain_left.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/upTerrian/upTerrain_left.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/upTerrian/upTerrain_middle.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/upTerrian/upTerrain_middle.png.meta
  SimpleStory/Assets/Pixel Adventure 1/Terrain/upTerrian/upTerrain_right.png
  SimpleStory/Assets/Pixel Adventure 1/Terrain/upTerrian/upTerrain_right.png.meta
  SimpleStory/Assets/Scenes/FirstLevel.unity
  SimpleStory/Assets/Scenes/FirstLevel.unity.meta
  SimpleStory/Assets/Scenes/Menu.unity
  SimpleStory/Assets/Scenes/PlayerTest.unity
  SimpleStory/Assets/Scripts/Creatures/.idea/.idea.Creatures.dir/.idea/.gitignore
  SimpleStory/Assets/Scripts/Creatures/.idea/.idea.Creatures.dir/.idea/encodings.xml
  SimpleStory/Assets/Scripts/Creatures/.idea/.idea.Creatures.dir/.idea/indexLayout.xml
  SimpleStory/Assets/Scripts/Creatures/.idea/.idea.Creatures.dir/.idea/riderModule.iml
  SimpleStory/Assets/Scripts/Creatures/.idea/.idea.Creatures.dir/.idea/vcs.xml
  SimpleStory/Assets/Scripts/Menu.cs
  SimpleStory/ProjectSettings/EditorBuildSettings.asset
Labels: bug, frontend
